version: '3'

services:
  flask_mask_app:
    container_name: pythonProject6
    restart: always
    build: ./pythonProject6
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app
  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_mask_app